# -*- coding: utf-8 -*-
"""AplicacionPaper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qe_5erSoi5B3IOmM4v7ow90VUC6g2wGG
"""

# -*- coding: utf-8 -*-
"""
ANÁLISIS PROBABILÍSTICO Y ESTADÍSTICO DE DENGUE
================================================

Código listo para Google Colab.

Este programa construye un ejemplo práctico basado en el trabajo académico
sobre modelado probabilístico. La lógica del proyecto es:

1. Generar o cargar datos mensuales de variables climáticas, sociales y epidemiológicas.
2. Modelar la relación entre variables con una estructura tipo copula gaussiana
   para simular dependencia entre factores.
3. Ajustar un modelo Poisson para predecir el número de casos.
4. Ajustar un modelo logístico para estimar la probabilidad de brote.
5. Mostrar tablas, gráficas, métricas y escenarios de intervención.

Variables usadas:
- temperature
- rainfall
- humidity
- population_density
- water_access
- sanitation_index
- mosquito_index
- lag_cases
- cases
- outbreak

El código está ampliamente comentado para que puedas explicarlo en clase.
"""

# ============================================================
# 0. INSTALACIÓN / IMPORTACIÓN DE LIBRERÍAS
# ============================================================

import sys
import subprocess
import pkgutil
import warnings

warnings.filterwarnings("ignore")


def ensure_package(import_name: str, pip_name: str = None):
    """
    Instala una librería si no está disponible en el entorno.
    Pensado para Google Colab.
    """
    if pkgutil.find_loader(import_name) is None:
        pkg = pip_name if pip_name is not None else import_name
        subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", pkg])


# Paquetes base
ensure_package("numpy")
ensure_package("pandas")
ensure_package("matplotlib")
ensure_package("scipy")
ensure_package("sklearn", "scikit-learn")
ensure_package("statsmodels")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from matplotlib.patches import FancyBboxPatch
from scipy import stats

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    roc_curve,
)

import statsmodels.api as sm

# En Colab existe display; si no, usamos print como respaldo.
try:
    from IPython.display import display
except Exception:
    def display(obj):
        print(obj)

plt.style.use("default")
np.set_printoptions(suppress=True, precision=4)


# ============================================================
# 1. CLASE PRINCIPAL
# ============================================================

class DengueProbabilisticAnalysis:
    """
    Clase principal para el análisis probabilístico del dengue.

    Estructura matemática del modelo:
    ----------------------------------
    1) Dependencia entre variables mediante una idea tipo copula gaussiana:
       Z ~ N(0, Sigma)
       U = Phi(Z)
       donde Phi es la CDF normal estándar.

    2) Modelo Poisson para los casos:
       Y_t ~ Poisson(lambda_t)
       log(lambda_t) = beta_0 + beta_1 X_1 + ... + beta_k X_k

    3) Modelo logístico para brote:
       P(Brote_t = 1) = 1 / (1 + exp(-(gamma_0 + gamma_1 X_1 + ... + gamma_k X_k)))

    El objetivo es que el flujo se parezca a un trabajo real de probabilidad y estadística.
    """

    def __init__(self, seed: int = 42, n_months: int = 72):
        """
        Parámetros
        ----------
        seed : int
            Semilla para reproducibilidad.
        n_months : int
            Número de observaciones mensuales sintéticas.
        """
        self.seed = seed
        self.n_months = n_months
        self.rng = np.random.default_rng(seed)

        # Variables que usaremos en el modelo
        self.feature_cols = [
            "temperature",
            "rainfall",
            "humidity",
            "population_density",
            "water_access",
            "sanitation_index",
            "mosquito_index",
            "lag_cases",
        ]

        # Contenedores para los datos y modelos
        self.data = None
        self.train_df = None
        self.test_df = None

        self.poisson_result = None
        self.nb_result = None
        self.logit_result = None

        # Escalado hecho con el conjunto de entrenamiento
        self.scaler_means = {}
        self.scaler_stds = {}

        # Resultados de predicción
        self.poisson_test_pred = None
        self.logit_test_prob = None
        self.logit_test_pred = None

        # Generar datos sintéticos por defecto
        self.data = self._generate_synthetic_data()

    # ========================================================
    # 2. GENERACIÓN DE DATOS SINTÉTICOS
    # ========================================================

    def _generate_synthetic_data(self) -> pd.DataFrame:
        """
        Genera un conjunto de datos sintéticos mensuales con dependencia
        probabilística entre variables usando una lógica tipo copula gaussiana.

        Esta parte es útil porque, aunque no tengas datos reales todavía,
        te permite mostrar el procedimiento completo en clase.
        """

        # Fechas mensuales
        dates = pd.date_range(start="2019-01-01", periods=self.n_months, freq="MS")
        t = np.arange(self.n_months)

        # Componentes estacionales
        seasonal_sin = np.sin(2 * np.pi * t / 12)
        seasonal_cos = np.cos(2 * np.pi * t / 12)

        # Matriz de correlación para simular dependencia entre factores latentes
        # (idea tipo Gaussian Copula)
        corr = np.array([
            [1.0,  0.45, 0.35, 0.10, 0.20],
            [0.45, 1.0,  0.40, 0.10, 0.15],
            [0.35, 0.40, 1.0,  0.05, 0.10],
            [0.10, 0.10, 0.05, 1.0,  0.20],
            [0.20, 0.15, 0.10, 0.20, 1.0],
        ])

        # Variables latentes normales correlacionadas
        latent = self.rng.multivariate_normal(
            mean=np.zeros(5),
            cov=corr,
            size=self.n_months
        )

        # Transformación a uniformes [0,1]
        u = stats.norm.cdf(latent)
        u = np.clip(u, 1e-6, 1 - 1e-6)

        # Variables observadas
        temperature = 24.5 + 2.8 * seasonal_sin + 0.9 * latent[:, 0]
        rainfall = 70 + 55 * (1 + seasonal_cos) / 2 + stats.gamma.ppf(u[:, 1], a=2.3, scale=18)
        humidity = 78 + 5.5 * seasonal_sin + 2.5 * latent[:, 2]
        population_density = 1100 + 2.0 * t + 28 * latent[:, 3]
        water_access = 0.89 - 0.02 * (1 + seasonal_cos) / 2 + 0.015 * latent[:, 4]
        sanitation_index = 0.81 + 0.015 * seasonal_cos - 0.02 * np.abs(latent[:, 0])

        # Aseguramos límites realistas
        water_access = np.clip(water_access, 0.65, 0.98)
        sanitation_index = np.clip(sanitation_index, 0.60, 0.97)

        # Índice del vector (mosquito index)
        # Subirá con lluvia y humedad, bajará con mayor acceso a agua/saneamiento
        mosquito_linear = (
            -1.6
            + 0.015 * (rainfall - 100)
            + 0.060 * (humidity - 75)
            - 0.030 * (temperature - 24)
            + 2.3 * (1 - water_access)
            + 1.8 * (1 - sanitation_index)
        )

        mosquito_index = 1 / (1 + np.exp(-mosquito_linear))
        mosquito_index += 0.04 * self.rng.normal(size=self.n_months)
        mosquito_index = np.clip(mosquito_index, 0, 1)

        # Generación recursiva de casos con dependencia temporal
        # Y_t ~ Poisson(lambda_t)
        cases = np.zeros(self.n_months, dtype=int)
        cases[0] = int(self.rng.poisson(lam=25))

        for i in range(1, self.n_months):
            lag = cases[i - 1]

            # Estructura del riesgo: log(lambda_t)
            linear_risk = (
                1.20
                + 0.030 * (temperature[i] - 24)
                + 0.012 * ((rainfall[i] - 100) / 10)
                + 0.035 * (humidity[i] - 78)
                - 2.2 * (water_access[i] - 0.80)
                - 1.7 * (sanitation_index[i] - 0.75)
                + 1.9 * mosquito_index[i]
                + 0.0035 * lag
                + 0.00020 * (population_density[i] - 1100)
            )

            lam = np.exp(linear_risk)
            lam = max(lam, 1.0)
            cases[i] = int(self.rng.poisson(lam=lam))

        # Variable de brote: 1 si los casos están por encima del percentil 75
        threshold = np.quantile(cases, 0.75)
        outbreak = (cases >= threshold).astype(int)

        # Armamos el DataFrame
        df = pd.DataFrame({
            "date": dates,
            "temperature": np.round(temperature, 2),
            "rainfall": np.round(rainfall, 2),
            "humidity": np.round(humidity, 2),
            "population_density": np.round(population_density, 2),
            "water_access": np.round(water_access, 4),
            "sanitation_index": np.round(sanitation_index, 4),
            "mosquito_index": np.round(mosquito_index, 4),
            "cases": cases,
            "outbreak": outbreak,
        })

        # Variable rezagada
        df["lag_cases"] = df["cases"].shift(1)
        df.loc[0, "lag_cases"] = df.loc[0, "cases"]
        df["lag_cases"] = df["lag_cases"].astype(int)

        # Variables temporales auxiliares
        df["year"] = df["date"].dt.year
        df["month"] = df["date"].dt.month

        return df

    # ========================================================
    # 3. CARGA DE DATOS REALES
    # ========================================================

    def load_real_data(self, csv_path: str):
        """
        Carga un archivo CSV real con la misma estructura esperada.

        Columnas mínimas requeridas:
        - date
        - temperature
        - rainfall
        - humidity
        - population_density
        - water_access
        - sanitation_index
        - mosquito_index
        - cases

        Si el CSV no contiene outbreak ni lag_cases, el programa los construye.
        """

        df = pd.read_csv(csv_path)

        required_cols = {
            "date",
            "temperature",
            "rainfall",
            "humidity",
            "population_density",
            "water_access",
            "sanitation_index",
            "mosquito_index",
            "cases",
        }

        missing = required_cols - set(df.columns)
        if missing:
            raise ValueError(f"Faltan estas columnas obligatorias en el CSV: {missing}")

        df["date"] = pd.to_datetime(df["date"])
        df = df.sort_values("date").reset_index(drop=True)

        if "lag_cases" not in df.columns:
            df["lag_cases"] = df["cases"].shift(1)
            df.loc[0, "lag_cases"] = df.loc[0, "cases"]
            df["lag_cases"] = df["lag_cases"].fillna(df["cases"]).astype(int)

        if "outbreak" not in df.columns:
            threshold = np.quantile(df["cases"], 0.75)
            df["outbreak"] = (df["cases"] >= threshold).astype(int)

        df["year"] = df["date"].dt.year
        df["month"] = df["date"].dt.month

        self.data = df
        print("Datos reales cargados correctamente.")
        return self.data

    # ========================================================
    # 4. UTILIDADES DE PRESENTACIÓN
    # ========================================================

    def show_table(self, df: pd.DataFrame, title: str = ""):
        """
        Muestra una tabla de forma limpia en Colab.
        """
        if title:
            print(f"\n{title}")
            print("=" * len(title))
        display(df)

    def basic_info(self):
        """
        Muestra tablas de resumen para entender los datos.
        """
        print("\nINFORMACIÓN GENERAL DEL DATASET")
        print("=" * 40)
        print(f"Filas: {self.data.shape[0]}")
        print(f"Columnas: {self.data.shape[1]}")
        print("\nColumnas:", list(self.data.columns))

        self.show_table(self.data.head(10), "Primeros 10 registros")

        desc = self.data.describe().T
        self.show_table(desc.round(3), "Estadísticos descriptivos")

        annual = self.data.groupby("year")[["cases", "temperature", "rainfall", "humidity"]].mean().round(2)
        self.show_table(annual, "Promedios anuales")

        monthly = self.data.groupby("month")[["cases", "temperature", "rainfall", "humidity"]].mean().round(2)
        self.show_table(monthly, "Promedios por mes")

    # ========================================================
    # 5. GRÁFICAS EXPLORATORIAS
    # ========================================================

    def plot_cases_over_time(self):
        """
        Gráfica temporal de casos.
        """
        fig, ax = plt.subplots(figsize=(12, 5))
        ax.plot(self.data["date"], self.data["cases"], marker="o", linewidth=2)
        ax.set_title("Evolución temporal de casos de dengue")
        ax.set_xlabel("Fecha")
        ax.set_ylabel("Casos")
        ax.grid(True, alpha=0.3)
        plt.xticks(rotation=45)
        plt.tight_layout()
        plt.show()

    def plot_climate_over_time(self):
        """
        Gráfica temporal de variables climáticas principales.
        """
        fig, ax = plt.subplots(figsize=(12, 5))
        ax.plot(self.data["date"], self.data["temperature"], label="Temperatura")
        ax.plot(self.data["date"], self.data["rainfall"], label="Lluvia")
        ax.plot(self.data["date"], self.data["humidity"], label="Humedad")
        ax.set_title("Variables climáticas a lo largo del tiempo")
        ax.set_xlabel("Fecha")
        ax.set_ylabel("Valor")
        ax.legend()
        ax.grid(True, alpha=0.3)
        plt.xticks(rotation=45)
        plt.tight_layout()
        plt.show()

    def plot_correlation_matrix(self):
        """
        Matriz de correlación con matplotlib.
        """
        cols = self.feature_cols + ["cases", "outbreak"]
        corr = self.data[cols].corr()

        fig, ax = plt.subplots(figsize=(10, 8))
        im = ax.imshow(corr.values, cmap="viridis", aspect="auto")
        ax.set_xticks(np.arange(len(corr.columns)))
        ax.set_xticklabels(corr.columns, rotation=45, ha="right")
        ax.set_yticks(np.arange(len(corr.index)))
        ax.set_yticklabels(corr.index)

        for i in range(corr.shape[0]):
            for j in range(corr.shape[1]):
                ax.text(j, i, f"{corr.iloc[i, j]:.2f}", ha="center", va="center", color="white", fontsize=8)

        ax.set_title("Matriz de correlación")
        fig.colorbar(im, ax=ax, shrink=0.8)
        plt.tight_layout()
        plt.show()

    def plot_scatter_pairs(self):
        """
        Relación entre casos y algunas variables clave.
        """
        vars_to_plot = ["rainfall", "humidity", "mosquito_index", "water_access"]
        fig, axes = plt.subplots(2, 2, figsize=(12, 10))
        axes = axes.ravel()

        for ax, col in zip(axes, vars_to_plot):
            ax.scatter(self.data[col], self.data["cases"], alpha=0.7)
            ax.set_title(f"Casos vs {col}")
            ax.set_xlabel(col)
            ax.set_ylabel("Casos")
            ax.grid(True, alpha=0.2)

        plt.tight_layout()
        plt.show()

    def plot_workflow_diagram(self):
        """
        Diagrama del flujo metodológico.
        """
        fig, ax = plt.subplots(figsize=(15, 4))
        ax.set_xlim(0, 1)
        ax.set_ylim(0, 1)
        ax.axis("off")

        boxes = [
            (0.03, 0.35, 0.16, 0.30, "Datos\nclimáticos\ny sociales"),
            (0.23, 0.35, 0.16, 0.30, "Dependencia\n(Gaussian\nCopula)"),
            (0.43, 0.35, 0.16, 0.30, "Modelo\nPoisson\n(casos)"),
            (0.63, 0.35, 0.16, 0.30, "Modelo\nlogístico\n(brote)"),
            (0.83, 0.35, 0.14, 0.30, "Escenarios\ny decisiones"),
        ]

        for x, y, w, h, text in boxes:
            patch = FancyBboxPatch(
                (x, y), w, h,
                boxstyle="round,pad=0.02",
                linewidth=1.5,
                edgecolor="black",
                facecolor="#E8F0FE"
            )
            ax.add_patch(patch)
            ax.text(x + w / 2, y + h / 2, text, ha="center", va="center", fontsize=10)

        # Flechas
        for i in range(len(boxes) - 1):
            x1, y1, w1, h1, _ = boxes[i]
            x2, y2, w2, h2, _ = boxes[i + 1]
            ax.annotate(
                "",
                xy=(x2, y2 + h2 / 2),
                xytext=(x1 + w1, y1 + h1 / 2),
                arrowprops=dict(arrowstyle="->", lw=2)
            )

        ax.set_title("Flujo metodológico del análisis probabilístico", fontsize=14, pad=20)
        plt.tight_layout()
        plt.show()

    # ========================================================
    # 6. PREPARACIÓN PARA MODELADO
    # ========================================================

    def _split_train_test(self):
        """
        División temporal:
        - 80% entrenamiento
        - 20% prueba

        Se respeta el orden temporal para evitar fuga de información.
        """
        n_train = int(len(self.data) * 0.80)
        self.train_df = self.data.iloc[:n_train].copy()
        self.test_df = self.data.iloc[n_train:].copy()

    def _fit_scaler(self):
        """
        Calcula media y desviación estándar en entrenamiento
        para estandarizar variables.
        """
        for col in self.feature_cols:
            mean = self.train_df[col].mean()
            std = self.train_df[col].std()
            if std == 0:
                std = 1.0
            self.scaler_means[col] = mean
            self.scaler_stds[col] = std

    def _standardize_df(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Estandariza las variables usando la media y desviación del entrenamiento.
        """
        out = df.copy()
        for col in self.feature_cols:
            out[col] = (out[col] - self.scaler_means[col]) / self.scaler_stds[col]
        return out

    def _build_design_matrices(self):
        """
        Construye matrices X e y para Poisson y Logit.
        """
        self._split_train_test()
        self._fit_scaler()

        train_std = self._standardize_df(self.train_df)
        test_std = self._standardize_df(self.test_df)

        X_train = sm.add_constant(train_std[self.feature_cols], has_constant="add")
        X_test = sm.add_constant(test_std[self.feature_cols], has_constant="add")

        y_train_cases = self.train_df["cases"].astype(float)
        y_test_cases = self.test_df["cases"].astype(float)

        y_train_outbreak = self.train_df["outbreak"].astype(int)
        y_test_outbreak = self.test_df["outbreak"].astype(int)

        return X_train, X_test, y_train_cases, y_test_cases, y_train_outbreak, y_test_outbreak

    # ========================================================
    # 7. HERRAMIENTA SEGURA PARA EXTRAER EL PRIMER ESCALAR
    # ========================================================

    def _first_scalar(self, obj):
        """
        Extrae de forma segura el primer valor escalar de:
        - Series de pandas
        - DataFrames
        - arreglos numpy
        - listas

        Esto evita errores como KeyError: 0.
        """
        arr = np.asarray(obj).ravel()
        if arr.size == 0:
            raise ValueError("El objeto no contiene valores para extraer.")
        return float(arr[0])

    # ========================================================
    # 8. MODELO POISSON
    # ========================================================

    def fit_poisson_model(self):
        """
        Ajusta un modelo Poisson:

            log(lambda_t) = beta_0 + beta_1 x_1 + ... + beta_k x_k

        donde lambda_t es la media esperada de casos.

        También calcula una medida simple de sobre-dispersión.
        """
        X_train, X_test, y_train_cases, y_test_cases, _, _ = self._build_design_matrices()

        poisson_model = sm.GLM(
            y_train_cases,
            X_train,
            family=sm.families.Poisson()
        )
        self.poisson_result = poisson_model.fit()

        # Predicción en test
        self.poisson_test_pred = self.poisson_result.predict(X_test)

        # Diagnóstico simple de sobre-dispersión
        dispersion = self.poisson_result.pearson_chi2 / self.poisson_result.df_resid

        # Si la dispersión es alta, también ajustamos una versión binomial negativa
        if dispersion > 1.5:
            nb_model = sm.GLM(
                y_train_cases,
                X_train,
                family=sm.families.NegativeBinomial()
            )
            self.nb_result = nb_model.fit()
        else:
            self.nb_result = None

        print("\nMODELO POISSON")
        print("=" * 50)
        print(self.poisson_result.summary())
        print(f"\nÍndice de sobre-dispersión: {dispersion:.3f}")

        if self.nb_result is not None:
            print("\nMODELO BINOMIAL NEGATIVO (por sobre-dispersión)")
            print("=" * 50)
            print(self.nb_result.summary())

        return self.poisson_result

    def evaluate_poisson_model(self):
        """
        Evalúa el modelo Poisson en el conjunto de prueba.
        """
        _, X_test, _, y_test_cases, _, _ = self._build_design_matrices()
        y_pred = self.poisson_test_pred

        mae = mean_absolute_error(y_test_cases, y_pred)
        rmse = np.sqrt(mean_squared_error(y_test_cases, y_pred))
        r2 = r2_score(y_test_cases, y_pred)

        metrics_df = pd.DataFrame({
            "Métrica": ["MAE", "RMSE", "R2"],
            "Valor": [mae, rmse, r2]
        })

        self.show_table(metrics_df.round(4), "Métricas del modelo Poisson")

        pred_df = self.test_df[["date", "cases"]].copy()
        pred_df["predicted_cases"] = np.round(y_pred, 2)
        pred_df["error"] = np.round(pred_df["cases"] - pred_df["predicted_cases"], 2)

        self.show_table(pred_df.head(12), "Comparación casos reales vs predichos")

        return metrics_df, pred_df

    def plot_poisson_predictions(self):
        """
        Gráfica de comparación entre casos reales y predichos.
        """
        if self.poisson_test_pred is None:
            raise RuntimeError("Primero debes ajustar el modelo Poisson.")

        fig, ax = plt.subplots(figsize=(12, 5))
        ax.plot(self.test_df["date"], self.test_df["cases"], marker="o", label="Casos reales")
        ax.plot(self.test_df["date"], self.poisson_test_pred, marker="o", label="Casos predichos")
        ax.set_title("Comparación entre casos reales y predichos")
        ax.set_xlabel("Fecha")
        ax.set_ylabel("Casos")
        ax.legend()
        ax.grid(True, alpha=0.3)
        plt.xticks(rotation=45)
        plt.tight_layout()
        plt.show()

        fig, ax = plt.subplots(figsize=(6, 6))
        ax.scatter(self.test_df["cases"], self.poisson_test_pred, alpha=0.8)
        lims = [
            min(self.test_df["cases"].min(), self.poisson_test_pred.min()),
            max(self.test_df["cases"].max(), self.poisson_test_pred.max())
        ]
        ax.plot(lims, lims, "r--")
        ax.set_title("Casos reales vs casos predichos")
        ax.set_xlabel("Casos reales")
        ax.set_ylabel("Casos predichos")
        ax.grid(True, alpha=0.3)
        plt.tight_layout()
        plt.show()

    # ========================================================
    # 9. MODELO LOGÍSTICO PARA BROTE
    # ========================================================

    def fit_logistic_model(self):
        """
        Ajusta un modelo logístico para brote:

            P(outbreak = 1) = 1 / (1 + exp(-(gamma_0 + gamma_1 x_1 + ...)))

        """
        X_train, X_test, _, _, y_train_outbreak, y_test_outbreak = self._build_design_matrices()

        try:
            logit_model = sm.Logit(y_train_outbreak, X_train)
            self.logit_result = logit_model.fit(disp=False, maxiter=200)
        except Exception:
            # Si hay problemas de convergencia, usamos regularización
            logit_model = sm.Logit(y_train_outbreak, X_train)
            self.logit_result = logit_model.fit_regularized(alpha=0.01, disp=False)

        self.logit_test_prob = self.logit_result.predict(X_test)
        self.logit_test_pred = (self.logit_test_prob >= 0.5).astype(int)

        print("\nMODELO LOGÍSTICO")
        print("=" * 50)
        print(self.logit_result.summary())

        return self.logit_result

    def evaluate_logistic_model(self):
        """
        Evalúa el modelo logístico con métricas de clasificación.
        """
        _, X_test, _, _, _, y_test_outbreak = self._build_design_matrices()

        y_prob = self.logit_test_prob
        y_pred = self.logit_test_pred

        acc = accuracy_score(y_test_outbreak, y_pred)
        prec = precision_score(y_test_outbreak, y_pred, zero_division=0)
        rec = recall_score(y_test_outbreak, y_pred, zero_division=0)
        f1 = f1_score(y_test_outbreak, y_pred, zero_division=0)

        try:
            auc = roc_auc_score(y_test_outbreak, y_prob)
        except Exception:
            auc = np.nan

        metrics_df = pd.DataFrame({
            "Métrica": ["Accuracy", "Precision", "Recall", "F1", "ROC AUC"],
            "Valor": [acc, prec, rec, f1, auc]
        })

        self.show_table(metrics_df.round(4), "Métricas del modelo logístico")

        cm = confusion_matrix(y_test_outbreak, y_pred)
        cm_df = pd.DataFrame(cm, index=["Real 0", "Real 1"], columns=["Pred 0", "Pred 1"])
        self.show_table(cm_df, "Matriz de confusión")

        return metrics_df, cm_df

    def plot_logistic_diagnostics(self):
        """
        Curva ROC y matriz de confusión en formato gráfico.
        """
        _, X_test, _, _, _, y_test_outbreak = self._build_design_matrices()

        # ROC
        try:
            fpr, tpr, _ = roc_curve(y_test_outbreak, self.logit_test_prob)
            fig, ax = plt.subplots(figsize=(7, 6))
            ax.plot(fpr, tpr, label="ROC")
            ax.plot([0, 1], [0, 1], "r--", label="Aleatorio")
            ax.set_title("Curva ROC del modelo logístico")
            ax.set_xlabel("False Positive Rate")
            ax.set_ylabel("True Positive Rate")
            ax.legend()
            ax.grid(True, alpha=0.3)
            plt.tight_layout()
            plt.show()
        except Exception:
            print("No fue posible construir la curva ROC con estos datos.")

        # Confusion matrix
        cm = confusion_matrix(y_test_outbreak, self.logit_test_pred)
        fig, ax = plt.subplots(figsize=(5, 5))
        im = ax.imshow(cm, cmap="Blues")
        ax.set_xticks([0, 1])
        ax.set_yticks([0, 1])
        ax.set_xticklabels(["Pred 0", "Pred 1"])
        ax.set_yticklabels(["Real 0", "Real 1"])
        ax.set_title("Matriz de confusión")
        for i in range(cm.shape[0]):
            for j in range(cm.shape[1]):
                ax.text(j, i, cm[i, j], ha="center", va="center", fontsize=12)
        fig.colorbar(im, ax=ax, shrink=0.8)
        plt.tight_layout()
        plt.show()

    # ========================================================
    # 10. TABLA DE COEFICIENTES
    # ========================================================

    def coefficient_table(self):
        """
        Tabla resumida de coeficientes para explicar la dirección del efecto.
        """
        if self.poisson_result is None or self.logit_result is None:
            raise RuntimeError("Primero ajusta ambos modelos.")

        poisson_coef = pd.DataFrame({
            "Variable": self.poisson_result.params.index,
            "Coef_Poisson": self.poisson_result.params.values,
            "p_value_Poisson": self.poisson_result.pvalues.values
        })

        logit_coef = pd.DataFrame({
            "Variable": self.logit_result.params.index,
            "Coef_Logit": self.logit_result.params.values
        })

        coef_df = poisson_coef.merge(logit_coef, on="Variable", how="outer")
        self.show_table(coef_df.round(4), "Coeficientes de los modelos")

        return coef_df

    # ========================================================
    # 11. ESCENARIOS DE INTERVENCIÓN
    # ========================================================

    def _transform_single_row(self, row: pd.Series) -> pd.DataFrame:
        """
        Estandariza una sola fila usando estadísticas del entrenamiento.
        """
        x = row[self.feature_cols].copy()

        for col in self.feature_cols:
            x[col] = (x[col] - self.scaler_means[col]) / self.scaler_stds[col]

        x = pd.DataFrame([x])
        x = sm.add_constant(x, has_constant="add")
        return x

    def scenario_analysis(self):
        """
        Simula distintos escenarios para mostrar cómo cambian
        la cantidad esperada de casos y la probabilidad de brote.

        Esto es muy útil para conectar el análisis estadístico
        con decisiones de salud pública.
        """
        if self.poisson_result is None or self.logit_result is None:
            raise RuntimeError("Primero ajusta los modelos.")

        base = self.data.iloc[-1].copy()

        scenarios = {
            "Escenario base": base.copy(),
            "Mejor acceso a agua y saneamiento": base.copy(),
            "Control vectorial": base.copy(),
            "Escenario climático adverso": base.copy(),
        }

        # Escenario 2: mejora del acceso a agua y saneamiento
        scenarios["Mejor acceso a agua y saneamiento"]["water_access"] = min(base["water_access"] + 0.08, 0.99)
        scenarios["Mejor acceso a agua y saneamiento"]["sanitation_index"] = min(base["sanitation_index"] + 0.08, 0.99)
        scenarios["Mejor acceso a agua y saneamiento"]["mosquito_index"] = max(base["mosquito_index"] - 0.10, 0.01)

        # Escenario 3: control vectorial
        scenarios["Control vectorial"]["mosquito_index"] = max(base["mosquito_index"] - 0.20, 0.01)
        scenarios["Control vectorial"]["rainfall"] = max(base["rainfall"] - 8, 1.0)

        # Escenario 4: clima adverso
        scenarios["Escenario climático adverso"]["temperature"] = base["temperature"] + 1.5
        scenarios["Escenario climático adverso"]["rainfall"] = base["rainfall"] + 25
        scenarios["Escenario climático adverso"]["humidity"] = base["humidity"] + 6
        scenarios["Escenario climático adverso"]["mosquito_index"] = min(base["mosquito_index"] + 0.15, 0.99)

        rows = []
        for name, row in scenarios.items():
            x = self._transform_single_row(row)

            # Extracción segura del primer valor numérico.
            # Esto evita errores como KeyError: 0 cuando predict devuelve una Serie.
            pred_cases = self._first_scalar(self.poisson_result.predict(x))
            pred_prob = self._first_scalar(self.logit_result.predict(x))

            rows.append({
                "Escenario": name,
                "Casos_esperados": round(pred_cases, 2),
                "Probabilidad_brote": round(pred_prob, 4)
            })

        scenario_df = pd.DataFrame(rows)
        self.show_table(scenario_df, "Análisis de escenarios")

        # Gráfica de barras
        fig, ax = plt.subplots(figsize=(10, 5))
        ax.bar(scenario_df["Escenario"], scenario_df["Casos_esperados"])
        ax.set_title("Casos esperados por escenario")
        ax.set_ylabel("Casos esperados")
        ax.tick_params(axis="x", rotation=20)
        ax.grid(True, axis="y", alpha=0.3)
        plt.tight_layout()
        plt.show()

        fig, ax = plt.subplots(figsize=(10, 5))
        ax.bar(scenario_df["Escenario"], scenario_df["Probabilidad_brote"])
        ax.set_title("Probabilidad de brote por escenario")
        ax.set_ylabel("Probabilidad")
        ax.tick_params(axis="x", rotation=20)
        ax.grid(True, axis="y", alpha=0.3)
        plt.tight_layout()
        plt.show()

        return scenario_df

    # ========================================================
    # 12. INFORME FINAL DE RESULTADOS
    # ========================================================

    def full_report(self):
        """
        Ejecuta todo el flujo analítico:
        - descripción del dataset
        - gráficas
        - modelos
        - métricas
        - coeficientes
        - escenarios

        Recomendación: correr este método al final.
        """
        print("\n====================================================")
        print("INICIO DEL ANÁLISIS PROBABILÍSTICO DEL DENGUE")
        print("====================================================")

        self.basic_info()

        self.plot_cases_over_time()
        self.plot_climate_over_time()
        self.plot_correlation_matrix()
        self.plot_scatter_pairs()
        self.plot_workflow_diagram()

        self.fit_poisson_model()
        self.evaluate_poisson_model()
        self.plot_poisson_predictions()

        self.fit_logistic_model()
        self.evaluate_logistic_model()
        self.plot_logistic_diagnostics()

        self.coefficient_table()
        self.scenario_analysis()

        print("\n====================================================")
        print("FIN DEL ANÁLISIS")
        print("====================================================")


# ============================================================
# 13. EJECUCIÓN DEL EJEMPLO
# ============================================================

# Si quieres usar datos sintéticos, deja esto así.
# Si más adelante tienes un CSV real, primero carga:
#
# analysis = DengueProbabilisticAnalysis()
# analysis.load_real_data("/content/tu_archivo.csv")
# analysis.full_report()
#
# Si no, ejecuta directamente el ejemplo sintético:

analysis = DengueProbabilisticAnalysis(seed=42, n_months=72)
analysis.full_report()