# -*- coding: utf-8 -*-
"""Statsmodel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_EL5GqY4hDJfCHgv36l2Ks4gBzSgBOd0
"""

import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt

def generar_datos(n=80, seed=42):
    """
    Genera un conjunto de datos sintéticos siguiendo una relación lineal.

    Parámetros:
    - n (int): Número de observaciones (puntos).
    - seed (int): Semilla para que los números aleatorios sean siempre los mismos.

    Retorna:
    - pd.DataFrame: Un set de datos con las columnas 'x' e 'y'.
    """
    np.random.seed(seed) # Mantiene la reproducibilidad

    # Creamos la variable independiente (X) de 0 a 10
    X = np.linspace(0, 10, n)

    # Creamos la variable dependiente (Y) basándonos en: y = beta0 + beta1*x + error
    # beta0 (intercepto) = 1.0 | beta1 (pendiente) = 2.5
    ruido = np.random.normal(scale=3.0, size=n) # Error aleatorio (distribución normal)
    y = 1.0 + 2.5 * X + ruido

    return pd.DataFrame({'x': X, 'y': y})

def ajustar_ols(df):
    """
    Calcula la regresión mediante Mínimos Cuadrados Ordinarios (OLS).

    Parámetros:
    - df (pd.DataFrame): El dataframe con los datos.

    Retorna:
    - results: El objeto con todos los estadísticos del modelo ajustado.
    """
    # statsmodels no añade el intercepto (beta0) automáticamente.
    # sm.add_constant agrega una columna de '1s' para calcularlo.
    X_con_intercepto = sm.add_constant(df['x'])

    # Creamos el modelo OLS (y ~ x)
    model = sm.OLS(df['y'], X_con_intercepto)

    # Ajustamos el modelo (entrenamiento)
    results = model.fit()
    return results

def graficar_y_guardar(df, results, nombre_archivo='RegresionLinealSimpleConStatsmodels.png'):
    """
    Crea una visualización de alta calidad y guarda el archivo para LaTeX.

    Parámetros:
    - df: Datos originales.
    - results: Resultado del ajuste OLS.
    - nombre_archivo: El nombre con el que se guardará el PNG.
    """
    # Obtenemos los valores predichos por el modelo para dibujar la línea
    df_temp = df.copy()
    df_temp['y_pred'] = results.fittedvalues

    # Configuración estética de la gráfica
    plt.figure(figsize=(10, 6))

    # 1. Dibujar los puntos reales (Scatter plot)
    plt.scatter(df_temp['x'], df_temp['y'], color='#3498db', alpha=0.7, label='Datos observados (Reales)')

    # 2. Dibujar la línea de tendencia (Regression line)
    plt.plot(df_temp['x'], df_temp['y_pred'], color='#e67e22', linewidth=3, label='Ajuste del Modelo (OLS)')

    # Títulos y etiquetas (importante para el reporte)
    plt.title('Visualización del Modelo de Regresión Lineal', fontsize=14)
    plt.xlabel('Variable Independiente (X)', fontsize=12)
    plt.ylabel('Variable Dependiente (Y)', fontsize=12)
    plt.legend() # Muestra la leyenda de colores
    plt.grid(True, linestyle='--', alpha=0.5) # Añade una cuadrícula suave

    # Guardar la imagen con alta resolución para que se vea bien en el PDF final
    plt.savefig(nombre_archivo, dpi=300, bbox_inches='tight')

    # Mostrar en pantalla (para compiladores online)
    plt.show()

def main():
    """
    Función principal que orquestra el flujo del programa.
    """
    print("--- Iniciando Proceso de Regresión ---\n")

    # Paso 1: Obtener datos
    datos = generar_datos()

    # Paso 2: Realizar el cálculo estadístico
    modelo_ajustado = ajustar_ols(datos)

    # Paso 3: Imprimir el reporte detallado en consola
    # Este reporte contiene el R-squared, P-values, etc.
    print(modelo_ajustado.summary())

    # Paso 4: Generar la gráfica para el documento LaTeX
    graficar_y_guardar(datos, modelo_ajustado)

    print(f"\n✅ Proceso completado. La imagen se guardó como 'RegresionLinealSimpleConStatsmodels.png'")

# Punto de entrada del script
if __name__ == '__main__':
    main()